// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSjub-ExM-HhHJRb4EX4Xw1gfOG1TeOE4',
    appId: '1:1082115627211:web:eb0737e6e6601339f0634e',
    messagingSenderId: '1082115627211',
    projectId: 'nifty-12516',
    authDomain: 'nifty-12516.firebaseapp.com',
    storageBucket: 'nifty-12516.firebasestorage.app',
    measurementId: 'G-EVSP9BVRH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANZWa7vRocjOhXcIokn4jRhYV1dkLXfAk',
    appId: '1:1082115627211:android:2780367221a3b7e2f0634e',
    messagingSenderId: '1082115627211',
    projectId: 'nifty-12516',
    storageBucket: 'nifty-12516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApz3UJAUkSFdJVtmEuB2eoYErs3fSYcN4',
    appId: '1:1082115627211:ios:af0787ca8df6a30cf0634e',
    messagingSenderId: '1082115627211',
    projectId: 'nifty-12516',
    storageBucket: 'nifty-12516.firebasestorage.app',
    iosClientId: '1082115627211-72urkv97j6r6d3aagvfs25qgpq9sa30u.apps.googleusercontent.com',
    iosBundleId: 'com.example.madproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApz3UJAUkSFdJVtmEuB2eoYErs3fSYcN4',
    appId: '1:1082115627211:ios:af0787ca8df6a30cf0634e',
    messagingSenderId: '1082115627211',
    projectId: 'nifty-12516',
    storageBucket: 'nifty-12516.firebasestorage.app',
    iosClientId: '1082115627211-72urkv97j6r6d3aagvfs25qgpq9sa30u.apps.googleusercontent.com',
    iosBundleId: 'com.example.madproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSjub-ExM-HhHJRb4EX4Xw1gfOG1TeOE4',
    appId: '1:1082115627211:web:6639a7cd3641983ef0634e',
    messagingSenderId: '1082115627211',
    projectId: 'nifty-12516',
    authDomain: 'nifty-12516.firebaseapp.com',
    storageBucket: 'nifty-12516.firebasestorage.app',
    measurementId: 'G-XDFZ76B1SZ',
  );
}
